#!/bin/bash

CURR_FOLDER="./tests/"
SUPPRESSION_FILE="${CURR_FOLDER}suppressions.supp"
LOG_FILE="${CURR_FOLDER}valgrind-out.txt"
EXEC="./minishell"

valgrind --leak-check=full \
         --show-leak-kinds=all \
         --suppressions=${SUPPRESSION_FILE} \
         --log-file=${LOG_FILE} \
         ${EXEC}
# --leak-check=full: "each individual leak will be shown in detail"

# --show-leak-kinds=all: Show all of "definite, indirect, possible,
#    reachable" leak kinds in the "full" report.

# --track-origins=yes: Favor useful output over speed. This tracks the origins
#    of uninitialized values, which could be very useful for memory errors.
#    Consider turning off if Valgrind is unacceptably slow.

# --verbose: Can tell you about unusual behavior of your program.
#    Repeat for more verbosity.

# --log-file: Write to a file. Useful when output exceeds terminal space.
